apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-my-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Adjust size as needed
  storageClassName: pharmacyvolumemanual  # StorageClass name
